export interface Country { name: string; code: string }

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan',                code: 'AF' },
  { name: 'Albania',                    code: 'AL' },
  { name: 'Algeria',                    code: 'DZ' },
  { name: 'Angola',                     code: 'AO' },
  { name: 'Argentina',                  code: 'AR' },
  { name: 'Armenia',                    code: 'AM' },
  { name: 'Australia',                  code: 'AU' },
  { name: 'Austria',                    code: 'AT' },
  { name: 'Azerbaijan',                 code: 'AZ' },
  { name: 'Bahrain',                    code: 'BH' },
  { name: 'Bangladesh',                 code: 'BD' },
  { name: 'Belarus',                    code: 'BY' },
  { name: 'Belgium',                    code: 'BE' },
  { name: 'Belize',                     code: 'BZ' },
  { name: 'Benin',                      code: 'BJ' },
  { name: 'Bhutan',                     code: 'BT' },
  { name: 'Bolivia',                    code: 'BO' },
  { name: 'Bosnia',                     code: 'BA' },
  { name: 'Botswana',                   code: 'BW' },
  { name: 'Brazil',                     code: 'BR' },
  { name: 'Brunei',                     code: 'BN' },
  { name: 'Bulgaria',                   code: 'BG' },
  { name: 'Burkina Faso',               code: 'BF' },
  { name: 'Burundi',                    code: 'BI' },
  { name: 'Cambodia',                   code: 'KH' },
  { name: 'Cameroon',                   code: 'CM' },
  { name: 'Canada',                     code: 'CA' },
  { name: 'Cape Verde',                 code: 'CV' },
  { name: 'Central African Republic',   code: 'CF' },
  { name: 'Chad',                       code: 'TD' },
  { name: 'Chile',                      code: 'CL' },
  { name: 'China',                      code: 'CN' },
  { name: 'Colombia',                   code: 'CO' },
  { name: 'Comoros',                    code: 'KM' },
  { name: 'Congo (Brazzaville)',        code: 'CG' },
  { name: 'Congo (Kinshasa)',           code: 'CD' },
  { name: 'Costa Rica',                 code: 'CR' },
  { name: 'Croatia',                    code: 'HR' },
  { name: 'Cuba',                       code: 'CU' },
  { name: 'Cyprus',                     code: 'CY' },
  { name: 'Czech Republic',             code: 'CZ' },
  { name: 'Denmark',                    code: 'DK' },
  { name: 'Djibouti',                   code: 'DJ' },
  { name: 'Dominican Republic',         code: 'DO' },
  { name: 'Ecuador',                    code: 'EC' },
  { name: 'Egypt',                      code: 'EG' },
  { name: 'El Salvador',                code: 'SV' },
  { name: 'Equatorial Guinea',          code: 'GQ' },
  { name: 'Eritrea',                    code: 'ER' },
  { name: 'Estonia',                    code: 'EE' },
  { name: 'Eswatini',                   code: 'SZ' },
  { name: 'Ethiopia',                   code: 'ET' },
  { name: 'Finland',                    code: 'FI' },
  { name: 'France',                     code: 'FR' },
  { name: 'Gabon',                      code: 'GA' },
  { name: 'Gambia',                     code: 'GM' },
  { name: 'Georgia',                    code: 'GE' },
  { name: 'Germany',                    code: 'DE' },
  { name: 'Ghana',                      code: 'GH' },
  { name: 'Greece',                     code: 'GR' },
  { name: 'Guatemala',                  code: 'GT' },
  { name: 'Guinea',                     code: 'GN' },
  { name: 'Guinea-Bissau',              code: 'GW' },
  { name: 'Honduras',                   code: 'HN' },
  { name: 'Hungary',                    code: 'HU' },
  { name: 'Iceland',                    code: 'IS' },
  { name: 'India',                      code: 'IN' },
  { name: 'Indonesia',                  code: 'ID' },
  { name: 'Iran',                       code: 'IR' },
  { name: 'Iraq',                       code: 'IQ' },
  { name: 'Ireland',                    code: 'IE' },
  { name: 'Israel',                     code: 'IL' },
  { name: 'Italy',                      code: 'IT' },
  { name: 'Ivory Coast',                code: 'CI' },
  { name: 'Jamaica',                    code: 'JM' },
  { name: 'Japan',                      code: 'JP' },
  { name: 'Jordan',                     code: 'JO' },
  { name: 'Kazakhstan',                 code: 'KZ' },
  { name: 'Kenya',                      code: 'KE' },
  { name: 'Kosovo',                     code: 'XK' },
  { name: 'Kuwait',                     code: 'KW' },
  { name: 'Kyrgyzstan',                 code: 'KG' },
  { name: 'Laos',                       code: 'LA' },
  { name: 'Latvia',                     code: 'LV' },
  { name: 'Lebanon',                    code: 'LB' },
  { name: 'Lesotho',                    code: 'LS' },
  { name: 'Liberia',                    code: 'LR' },
  { name: 'Libya',                      code: 'LY' },
  { name: 'Lithuania',                  code: 'LT' },
  { name: 'Luxembourg',                 code: 'LU' },
  { name: 'Madagascar',                 code: 'MG' },
  { name: 'Malawi',                     code: 'MW' },
  { name: 'Malaysia',                   code: 'MY' },
  { name: 'Maldives',                   code: 'MV' },
  { name: 'Mali',                       code: 'ML' },
  { name: 'Malta',                      code: 'MT' },
  { name: 'Mauritania',                 code: 'MR' },
  { name: 'Mauritius',                  code: 'MU' },
  { name: 'Mexico',                     code: 'MX' },
  { name: 'Moldova',                    code: 'MD' },
  { name: 'Mongolia',                   code: 'MN' },
  { name: 'Montenegro',                 code: 'ME' },
  { name: 'Morocco',                    code: 'MA' },
  { name: 'Mozambique',                 code: 'MZ' },
  { name: 'Myanmar',                    code: 'MM' },
  { name: 'Namibia',                    code: 'NA' },
  { name: 'Nepal',                      code: 'NP' },
  { name: 'Netherlands',                code: 'NL' },
  { name: 'New Zealand',                code: 'NZ' },
  { name: 'Nicaragua',                  code: 'NI' },
  { name: 'Niger',                      code: 'NE' },
  { name: 'Nigeria',                    code: 'NG' },
  { name: 'North Korea',                code: 'KP' },
  { name: 'North Macedonia',            code: 'MK' },
  { name: 'Norway',                     code: 'NO' },
  { name: 'Oman',                       code: 'OM' },
  { name: 'Pakistan',                   code: 'PK' },
  { name: 'Palestine',                  code: 'PS' },
  { name: 'Panama',                     code: 'PA' },
  { name: 'Paraguay',                   code: 'PY' },
  { name: 'Peru',                       code: 'PE' },
  { name: 'Philippines',                code: 'PH' },
  { name: 'Poland',                     code: 'PL' },
  { name: 'Portugal',                   code: 'PT' },
  { name: 'Qatar',                      code: 'QA' },
  { name: 'Romania',                    code: 'RO' },
  { name: 'Russia',                     code: 'RU' },
  { name: 'Rwanda',                     code: 'RW' },
  { name: 'São Tomé and Príncipe',      code: 'ST' },
  { name: 'Saudi Arabia',               code: 'SA' },
  { name: 'Senegal',                    code: 'SN' },
  { name: 'Serbia',                     code: 'RS' },
  { name: 'Seychelles',                 code: 'SC' },
  { name: 'Sierra Leone',               code: 'SL' },
  { name: 'Singapore',                  code: 'SG' },
  { name: 'Slovakia',                   code: 'SK' },
  { name: 'Slovenia',                   code: 'SI' },
  { name: 'Somalia',                    code: 'SO' },
  { name: 'South Africa',               code: 'ZA' },
  { name: 'South Korea',                code: 'KR' },
  { name: 'South Sudan',                code: 'SS' },
  { name: 'Spain',                      code: 'ES' },
  { name: 'Sri Lanka',                  code: 'LK' },
  { name: 'Sudan',                      code: 'SD' },
  { name: 'Sweden',                     code: 'SE' },
  { name: 'Switzerland',                code: 'CH' },
  { name: 'Syria',                      code: 'SY' },
  { name: 'Taiwan',                     code: 'TW' },
  { name: 'Tajikistan',                 code: 'TJ' },
  { name: 'Tanzania',                   code: 'TZ' },
  { name: 'Thailand',                   code: 'TH' },
  { name: 'Timor-Leste',                code: 'TL' },
  { name: 'Togo',                       code: 'TG' },
  { name: 'Trinidad and Tobago',        code: 'TT' },
  { name: 'Tunisia',                    code: 'TN' },
  { name: 'Turkey',                     code: 'TR' },
  { name: 'Turkmenistan',               code: 'TM' },
  { name: 'Uganda',                     code: 'UG' },
  { name: 'Ukraine',                    code: 'UA' },
  { name: 'United Arab Emirates',       code: 'AE' },
  { name: 'United Kingdom',             code: 'GB' },
  { name: 'United States',              code: 'US' },
  { name: 'Uruguay',                    code: 'UY' },
  { name: 'Uzbekistan',                 code: 'UZ' },
  { name: 'Venezuela',                  code: 'VE' },
  { name: 'Vietnam',                    code: 'VN' },
  { name: 'Yemen',                      code: 'YE' },
  { name: 'Zambia',                     code: 'ZM' },
  { name: 'Zimbabwe',                   code: 'ZW' },
]

const NAME_TO_CODE = Object.fromEntries(COUNTRIES.map(c => [c.name.toLowerCase(), c.code]))

const NATIONALITY_ALIASES: Record<string, string> = {
  // Europe
  'albanian': 'AL', 'austrian': 'AT', 'azerbaijani': 'AZ',
  'belarusian': 'BY', 'belgian': 'BE', 'bosnian': 'BA', 'brazilian': 'BR', 'bulgarian': 'BG',
  'canadian': 'CA', 'chilean': 'CL', 'colombian': 'CO', 'croatian': 'HR', 'cuban': 'CU',
  'cypriot': 'CY', 'czech': 'CZ', 'danish': 'DK',
  'dutch': 'NL', 'english': 'GB', 'estonian': 'EE',
  'finnish': 'FI', 'french': 'FR',
  'georgian': 'GE', 'german': 'DE', 'greek': 'GR',
  'hungarian': 'HU', 'icelander': 'IS', 'icelandic': 'IS', 'irish': 'IE', 'italian': 'IT',
  'kazakh': 'KZ', 'kosovar': 'XK', 'kyrgyz': 'KG',
  'latvian': 'LV', 'lithuanian': 'LT', 'luxembourger': 'LU',
  'macedonian': 'MK', 'maltese': 'MT', 'moldovan': 'MD', 'montenegrin': 'ME',
  'norwegian': 'NO', 'polish': 'PL', 'portuguese': 'PT',
  'romanian': 'RO', 'russian': 'RU',
  'scottish': 'GB', 'serbian': 'RS', 'slovak': 'SK', 'slovenian': 'SI', 'spanish': 'ES',
  'swedish': 'SE', 'swiss': 'CH', 'tajik': 'TJ', 'turkmen': 'TM',
  'ukrainian': 'UA', 'british': 'GB', 'uzbek': 'UZ', 'welsh': 'GB',
  // Americas
  'american': 'US', 'argentinian': 'AR', 'belizean': 'BZ', 'bolivian': 'BO',
  'costa rican': 'CR', 'dominican': 'DO', 'ecuadorian': 'EC',
  'guatemalan': 'GT', 'honduran': 'HN', 'jamaican': 'JM', 'mexican': 'MX',
  'nicaraguan': 'NI', 'panamanian': 'PA', 'paraguayan': 'PY', 'peruvian': 'PE',
  'salvadoran': 'SV', 'trinidadian': 'TT', 'tobagonian': 'TT',
  'uruguayan': 'UY', 'venezuelan': 'VE',
  // Asia & Middle East
  'afghan': 'AF', 'armenian': 'AM', 'australian': 'AU',
  'bahraini': 'BH', 'bangladeshi': 'BD', 'bhutanese': 'BT', 'bruneian': 'BN',
  'burmese': 'MM', 'cambodian': 'KH', 'chinese': 'CN',
  'emirati': 'AE', 'filipino': 'PH', 'indian': 'IN', 'indonesian': 'ID',
  'iranian': 'IR', 'iraqi': 'IQ', 'israeli': 'IL', 'japanese': 'JP',
  'jordanian': 'JO', 'kuwaiti': 'KW', 'laotian': 'LA', 'lao': 'LA',
  'lebanese': 'LB', 'malaysian': 'MY', 'maldivian': 'MV', 'mongolian': 'MN',
  'nepali': 'NP', 'new zealander': 'NZ', 'north korean': 'KP',
  'omani': 'OM', 'pakistani': 'PK', 'palestinian': 'PS', 'qatari': 'QA',
  'saudi': 'SA', 'saudi arabian': 'SA', 'singaporean': 'SG', 'south korean': 'KR',
  'korean': 'KR', 'sri lankan': 'LK', 'syrian': 'SY', 'taiwanese': 'TW',
  'thai': 'TH', 'timorese': 'TL', 'turkish': 'TR', 'vietnamese': 'VN', 'yemeni': 'YE',
  // Africa
  'algerian': 'DZ', 'angolan': 'AO', 'beninese': 'BJ', 'botswanan': 'BW',
  'burkinabe': 'BF', 'burundian': 'BI', 'cameroonian': 'CM', 'cape verdean': 'CV',
  'chadian': 'TD', 'comorian': 'KM', 'congolese': 'CG', 'djiboutian': 'DJ',
  'egyptian': 'EG', 'equatoguinean': 'GQ', 'eritrean': 'ER', 'ethiopian': 'ET',
  'swazi': 'SZ', 'gabonese': 'GA', 'gambian': 'GM', 'ghanaian': 'GH',
  'guinean': 'GN', 'bissau-guinean': 'GW', 'ivorian': 'CI',
  'kenyan': 'KE', 'basotho': 'LS', 'liberian': 'LR', 'libyan': 'LY',
  'malagasy': 'MG', 'malawian': 'MW', 'malian': 'ML', 'mauritanian': 'MR',
  'mauritian': 'MU', 'moroccan': 'MA', 'mozambican': 'MZ', 'namibian': 'NA',
  'nigerian': 'NG', 'nigerien': 'NE', 'rwandan': 'RW', 'sao tomean': 'ST',
  'senegalese': 'SN', 'seychellois': 'SC', 'sierra leonean': 'SL', 'somali': 'SO',
  'south african': 'ZA', 'south sudanese': 'SS', 'sudanese': 'SD',
  'tanzanian': 'TZ', 'togolese': 'TG', 'tunisian': 'TN', 'ugandan': 'UG',
  'zambian': 'ZM', 'zimbabwean': 'ZW',
}

export function countryFlag(nationality: string | null | undefined): string {
  if (!nationality) return ''
  const key = nationality.toLowerCase().trim()
  const code = NAME_TO_CODE[key] ?? NATIONALITY_ALIASES[key]
  if (!code) return ''
  return String.fromCodePoint(...[...code].map(c => 0x1F1A5 + c.charCodeAt(0)))
}
