import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import { notFound, redirect } from 'next/navigation'
import { prisma } from '@/lib/prisma'
import { getSession } from '@/lib/session'
import { resolveImageUrl } from '@/lib/data'
import { APP_URL, SITE_URL } from '@/lib/env'
import SocialShare from '@/components/SocialShare'
import HangoutJoinButton from '@/components/HangoutJoinButton'
import HangoutDiscussion from '@/components/HangoutDiscussion'
import AddToCalendar from '@/components/AddToCalendar'

// Read-only permalink for a single hangout. Designed so stale push
// notifications (cancellation, recap from days ago, third-party links)
// don't 404 — instead the user sees what the hangout was, what happened
// to it, and a way back to the live feed.
//
// Why server-rendered (no 'use client'): this page does no mutations.
// All actions (join, cancel, message) happen on the main /hangouts feed
// where the join/leave/message UI already lives. Duplicating that here
// would create two sources of truth.

export const dynamic = 'force-dynamic'  // session-gated; no caching

interface PageProps {
  params: Promise<{ id: string }>
}

function StatusBanner({ status, endsAt }: { status: string; endsAt: Date }) {
  if (status === 'cancelled') {
    return (
      <div className="rounded-2xl border border-red-200 bg-red-50 p-4">
        <p className="text-sm font-bold text-red-900">❌ This hangout was cancelled</p>
        <p className="text-xs text-red-700 mt-0.5">The host or a moderator called it off. Check the feed for other plans.</p>
      </div>
    )
  }
  if (status === 'expired' || endsAt < new Date()) {
    return (
      <div className="rounded-2xl border border-gray-200 bg-gray-50 p-4">
        <p className="text-sm font-bold text-gray-900">✓ This hangout has ended</p>
        <p className="text-xs text-gray-600 mt-0.5">
          Was a joiner? Leave a quick reference on the{' '}
          <Link href="/hangouts/recap" className="font-semibold text-amber-700 underline">recap page</Link>.
        </p>
      </div>
    )
  }
  return (
    <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 flex items-center justify-between gap-3">
      <p className="text-sm font-bold text-amber-900">This hangout is still open</p>
      <Link href="/hangouts" className="text-xs font-bold text-amber-700 bg-white border border-amber-300 hover:bg-amber-100 px-3 py-1.5 rounded-lg shrink-0">
        Open in feed →
      </Link>
    </div>
  )
}

// Public-safe link preview (WhatsApp/social) — runs for logged-out crawlers
// too, so it deliberately exposes only what/where/when, never member names.
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params
  const hangout = await prisma.hangout.findUnique({
    where:  { id },
    select: { title: true, location: true, neighborhood: true, startsAt: true, status: true, photo: true },
  })
  if (!hangout) return { title: 'Hangout · Smileys' }

  const when  = hangout.startsAt.toLocaleString('en-GB', { timeZone: 'Europe/Istanbul', weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })
  const where = [hangout.location, hangout.neighborhood].filter(Boolean).join(' · ')
  const title = `${hangout.title} · Smileys hangout`
  const desc  = hangout.status === 'cancelled'
    ? 'This hangout was cancelled.'
    : `📍 ${where} · 🕒 ${when} — join on Smileys.`

  // Preview image is generated by /api/og/hangout — the hangout's own photo with
  // a "HANGOUT" badge overlaid. Pass the photo as an absolute URL (uploads
  // resolve to /app/... → prefix SITE_URL; external URLs are already absolute).
  // Always set it: a photoless hangout gets the branded HANGOUT fallback card.
  const resolved = hangout.photo ? resolveImageUrl(hangout.photo) : ''
  const photoAbs = resolved
    ? (/^https?:\/\//i.test(resolved) ? resolved : `${SITE_URL}${resolved}`)
    : ''
  const ogImage = `${SITE_URL}/app/api/og/hangout${photoAbs ? `?photo=${encodeURIComponent(photoAbs)}` : ''}`

  return {
    title,
    description: desc,
    openGraph: { title, description: desc, type: 'website', images: [{ url: ogImage, width: 1200, height: 630 }] },
    twitter:   { card: 'summary_large_image', title, description: desc, images: [ogImage] },
  }
}

export default async function HangoutPermalinkPage({ params }: PageProps) {
  const { id } = await params
  const session = await getSession()
  // Land a shared link back on this exact hangout after sign-in, not the feed.
  if (!session) redirect(`/login?next=/hangouts/${id}`)

  const hangout = await prisma.hangout.findUnique({
    where: { id },
    include: {
      user: { select: { id: true, name: true, color: true, profilePhoto: true, goodHangouts: true, neighborhood: true } },
      joins: {
        orderBy: { createdAt: 'asc' },
        select: { user: { select: { id: true, name: true, color: true, profilePhoto: true } } },
      },
      messages: {
        orderBy: { createdAt: 'asc' },
        take: 50,
        select: { id: true, body: true, createdAt: true, user: { select: { id: true, name: true, color: true, profilePhoto: true } } },
      },
    },
  })

  if (!hangout) notFound()

  const hostAvatar = hangout.user.profilePhoto ? resolveImageUrl(hangout.user.profilePhoto) : null
  const photoUrl   = hangout.photo ? resolveImageUrl(hangout.photo) : null

  // Join affordance: only for non-hosts, and only while the hangout is still
  // live (active + not past). Host is implicitly in; ended/cancelled show the
  // status banner instead.
  const isOwner    = hangout.user.id === session.id
  const joinedByMe = hangout.joins.some((j: any) => j.user.id === session.id)
  const isJoinable = hangout.status === 'active' && hangout.endsAt >= new Date()

  // Directions — hangouts store only a text location, so open Maps with a
  // place search (opens the native maps app on mobile).
  const mapsQuery = [hangout.location, hangout.neighborhood, 'Istanbul'].filter(Boolean).join(', ')
  const mapsUrl   = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(mapsQuery)}`

  // Istanbul wall-clock start/end for Add-to-Calendar (h23 per the ICU gotcha).
  const tz = 'Europe/Istanbul'
  const startDate = hangout.startsAt.toLocaleDateString('en-CA', { timeZone: tz })
  const startTime = hangout.startsAt.toLocaleTimeString('en-GB', { timeZone: tz, hour: '2-digit', minute: '2-digit', hourCycle: 'h23' })
  const endDate   = hangout.endsAt.toLocaleDateString('en-CA', { timeZone: tz })
  const endTime   = hangout.endsAt.toLocaleTimeString('en-GB', { timeZone: tz, hour: '2-digit', minute: '2-digit', hourCycle: 'h23' })

  return (
    <div className="min-h-screen bg-warm pb-16">
      <div className="max-w-2xl mx-auto px-4 sm:px-6 pt-6 pb-6 space-y-4">
        <Link href="/hangouts" className="text-xs font-semibold text-amber-700 inline-flex items-center gap-1">
          ← Back to hangouts
        </Link>

        <StatusBanner status={hangout.status} endsAt={hangout.endsAt} />

        {/* Hero card */}
        <div className="bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden">
          {/* Host header — shown first so you immediately know who's hosting */}
          <div className="flex items-center gap-3 px-5 pt-5 pb-4">
            <Link href={`/members/${hangout.user.id}`} className="shrink-0">
              {hostAvatar
                ? <img src={hostAvatar} alt={hangout.user.name} className="w-12 h-12 rounded-full object-cover" />
                : <div className="w-12 h-12 rounded-full flex items-center justify-center text-white text-base font-bold"
                    style={{ backgroundColor: hangout.user.color }}>{hangout.user.name[0]}</div>}
            </Link>
            <div className="flex-1 min-w-0">
              <Link href={`/members/${hangout.user.id}`} className="text-sm font-bold text-gray-900 hover:text-amber-700">
                {hangout.user.name}
              </Link>
              <p className="text-xs text-gray-500">
                is hosting a hangout{hangout.user.neighborhood && <> · 📍 {hangout.user.neighborhood}</>}
              </p>
            </div>
            {hangout.user.goodHangouts > 0 && (
              <span className="inline-flex items-center gap-0.5 px-2 py-1 rounded-full bg-green-50 text-green-700 text-xs font-semibold border border-green-200 shrink-0">
                ✓ {hangout.user.goodHangouts} good
              </span>
            )}
          </div>

          {photoUrl && (
            <div className="relative w-full h-48 sm:h-64 bg-gray-100">
              <Image src={photoUrl} alt={hangout.title} fill className="object-cover" sizes="(max-width: 640px) 100vw, 640px" unoptimized />
            </div>
          )}
          <div className="p-5 space-y-3">
            <div className="flex items-start gap-2 flex-wrap">
              <h1 className="text-xl font-extrabold text-gray-900 flex-1 min-w-0">{hangout.title}</h1>
              {hangout.meetMode === 'solo' && (
                <span className="inline-flex items-center gap-0.5 px-2 py-1 rounded-full bg-purple-50 text-purple-700 text-xs font-semibold border border-purple-200 shrink-0">
                  1-on-1
                </span>
              )}
            </div>

            <div className="text-sm text-gray-700 space-y-1">
              <p>📍 <span className="font-medium">{hangout.location}</span>
                {hangout.neighborhood && <span className="text-gray-600"> · {hangout.neighborhood}</span>}
              </p>
              <p>🕒 <span className="font-medium">
                {hangout.startsAt.toLocaleString('en-GB', { timeZone: 'Europe/Istanbul', weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}
                {' – '}
                {hangout.endsAt.toLocaleTimeString('en-GB', { timeZone: 'Europe/Istanbul', hour: '2-digit', minute: '2-digit' })}
              </span></p>
            </div>

            {hangout.description && (
              <p className="text-sm text-gray-600 whitespace-pre-wrap pt-2 border-t border-gray-100">{hangout.description}</p>
            )}
          </div>
        </div>

        {/* Primary action — mirrors the feed's "I'm in", so a shared link is
            actionable right here instead of a dead end. */}
        {isOwner ? (
          <p className="text-center text-xs font-semibold text-gray-500">You're hosting this hangout</p>
        ) : isJoinable ? (
          <HangoutJoinButton hangoutId={hangout.id} initialJoined={joinedByMe} />
        ) : null}

        {/* Directions (always, so people can find the spot) + Add to Calendar
            (upcoming only). Hidden for cancelled hangouts. */}
        {hangout.status !== 'cancelled' && (
          <div className="flex items-center justify-center gap-3 flex-wrap">
            <a href={mapsUrl} target="_blank" rel="noopener noreferrer"
              className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-gray-200 text-gray-600 hover:bg-gray-50 hover:border-gray-300 text-sm font-semibold transition-colors">
              🗺️ Get directions
            </a>
            {isJoinable && (
              <AddToCalendar
                title={hangout.title}
                date={startDate} time={startTime}
                endDate={endDate} endTime={endTime}
                location={hangout.location}
                description={hangout.description ?? undefined}
                url={`${APP_URL}/hangouts/${id}`}
              />
            )}
          </div>
        )}

        {/* Joiners */}
        {hangout.joins.length > 0 && (
          <div className="bg-white border border-gray-100 rounded-2xl shadow-sm p-5">
            <p className="text-xs font-bold text-gray-600 uppercase tracking-widest mb-3">
              {hangout.joins.length} joiner{hangout.joins.length === 1 ? '' : 's'}
            </p>
            <div className="flex items-center gap-3 flex-wrap">
              {hangout.joins.map((j: any) => {
                const av = j.user.profilePhoto ? resolveImageUrl(j.user.profilePhoto) : null
                return (
                  <Link key={j.user.id} href={`/members/${j.user.id}`} className="flex items-center gap-2 text-xs">
                    {av
                      ? <img src={av} alt={j.user.name} className="w-7 h-7 rounded-full object-cover" />
                      : <div className="w-7 h-7 rounded-full flex items-center justify-center text-white text-[10px] font-bold"
                          style={{ backgroundColor: j.user.color }}>{j.user.name[0]}</div>}
                    <span className="font-medium text-gray-700">{j.user.name}</span>
                  </Link>
                )
              })}
            </div>
          </div>
        )}

        {/* Discussion — interactive thread. Host + joiners can post (the API
            gates it); non-members see it read-only with a nudge to join. */}
        <HangoutDiscussion
          hangoutId={hangout.id}
          initialMessages={hangout.messages}
          canPost={isOwner || joinedByMe}
          isJoinable={isJoinable}
        />

        {/* Share this hangout — the permalink is member-gated, so a non-member
            who opens it is nudged to sign in and can then join. */}
        <SocialShare title={`${hangout.title} — a Smileys hangout`} url={`${APP_URL}/hangouts/${id}`} />
      </div>
    </div>
  )
}
