ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "appealNote"   TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "appealStatus" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "appealedAt"   TIMESTAMP(3);
